// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationForm.DataBase;

namespace ReservationForm.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    [Migration("20220326140935_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReservationForm.Models.Rezervasyon", b =>
                {
                    b.Property<int>("rezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("KisilerFarkliVagonlaraYerlestirilebilir")
                        .HasColumnType("bit");

                    b.Property<int>("RezervasyonYapilacakKisiSayisi")
                        .HasColumnType("int");

                    b.HasKey("rezervasyonId");

                    b.ToTable("Rezervasyons");
                });

            modelBuilder.Entity("ReservationForm.Models.RezervasyonResults", b =>
                {
                    b.Property<int>("rezervasyonResultsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("rezervasyonYapilabilir")
                        .HasColumnType("bit");

                    b.HasKey("rezervasyonResultsId");

                    b.ToTable("RezervasyonResults");
                });

            modelBuilder.Entity("ReservationForm.Models.Tren", b =>
                {
                    b.Property<int>("trenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rezervasyonId")
                        .HasColumnType("int");

                    b.HasKey("trenId");

                    b.HasIndex("rezervasyonId");

                    b.ToTable("Tren");
                });

            modelBuilder.Entity("ReservationForm.Models.Vagonlar", b =>
                {
                    b.Property<int>("vagonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DolulukAdeti")
                        .HasColumnType("int");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int?>("trenId")
                        .HasColumnType("int");

                    b.HasKey("vagonId");

                    b.HasIndex("trenId");

                    b.ToTable("Vagonlar");
                });

            modelBuilder.Entity("ReservationForm.Models.YerlesimAyrinti", b =>
                {
                    b.Property<int>("yerlesimAyrintiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<string>("VagonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rezervasyonResultsId")
                        .HasColumnType("int");

                    b.HasKey("yerlesimAyrintiId");

                    b.HasIndex("rezervasyonResultsId");

                    b.ToTable("YerlesimAyrinti");
                });

            modelBuilder.Entity("ReservationForm.Models.Tren", b =>
                {
                    b.HasOne("ReservationForm.Models.Rezervasyon", null)
                        .WithMany("Trens")
                        .HasForeignKey("rezervasyonId");
                });

            modelBuilder.Entity("ReservationForm.Models.Vagonlar", b =>
                {
                    b.HasOne("ReservationForm.Models.Tren", null)
                        .WithMany("Vagonlars")
                        .HasForeignKey("trenId");
                });

            modelBuilder.Entity("ReservationForm.Models.YerlesimAyrinti", b =>
                {
                    b.HasOne("ReservationForm.Models.RezervasyonResults", null)
                        .WithMany("yerlesimAyrintis")
                        .HasForeignKey("rezervasyonResultsId");
                });

            modelBuilder.Entity("ReservationForm.Models.Rezervasyon", b =>
                {
                    b.Navigation("Trens");
                });

            modelBuilder.Entity("ReservationForm.Models.RezervasyonResults", b =>
                {
                    b.Navigation("yerlesimAyrintis");
                });

            modelBuilder.Entity("ReservationForm.Models.Tren", b =>
                {
                    b.Navigation("Vagonlars");
                });
#pragma warning restore 612, 618
        }
    }
}
